# Generated by Django 5.0.7 on 2024-07-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_institution_email_institution_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='institutionregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
