# Generated by Django 5.0.7 on 2024-07-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_contactmessage_institutionregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='institutionregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
