# Generated by Django 5.0.7 on 2024-07-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_employer_email_employer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
    ]
